/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface _SERVICE {
  'convertCurrency' : ActorMethod<[number, string, string], number>,
  'convertLength' : ActorMethod<[number, string, string], number>,
  'convertTemperature' : ActorMethod<[number, string, string], number>,
  'convertVolume' : ActorMethod<[number, string, string], number>,
  'convertWeight' : ActorMethod<[number, string, string], number>,
  'getLengthUnits' : ActorMethod<[], Array<string>>,
  'getSupportedCurrencies' : ActorMethod<[], Array<string>>,
  'getTemperatureUnits' : ActorMethod<[], Array<string>>,
  'getVolumeUnits' : ActorMethod<[], Array<string>>,
  'getWeightUnits' : ActorMethod<[], Array<string>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];