/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'convertCurrency' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Float64],
      ['query'],
    ),
  'convertLength' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Float64],
      ['query'],
    ),
  'convertTemperature' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Float64],
      ['query'],
    ),
  'convertVolume' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Float64],
      ['query'],
    ),
  'convertWeight' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Float64],
      ['query'],
    ),
  'getLengthUnits' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSupportedCurrencies' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTemperatureUnits' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getVolumeUnits' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getWeightUnits' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'convertCurrency' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'convertLength' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'convertTemperature' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'convertVolume' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'convertWeight' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'getLengthUnits' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSupportedCurrencies' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTemperatureUnits' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getVolumeUnits' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getWeightUnits' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };